package com.nezumi_ai.data.inference

import android.content.Context
import android.util.Log
import java.io.File

object CacheManager {
    private const val TAG = "CacheManager"
    private const val MAX_CACHE_SIZE_MB = 300   // ★ 最大キャッシュサイズ：300MB に削減（Gallery と同様）
    private const val CLEANUP_THRESHOLD_MB = 200  // ★ クリーンアップ開始：200MB に削減
    
    private var lastLoadedModelName = ""  // 現在読み込まれているモデル名キャッシュ
    private var recentCacheFiles = setOf<String>()  // 最近生成されたキャッシュ（この読み込みセッション中）
    
    /**
     * キャッシュディレクトリの使用量をチェックし、必要に応じてクリーンアップ
     * currentModelBaseName: 現在読み込むモデルのベース名（例: "gemma-3n-e4b"）
     *                       このモデルのキャッシュファイルは保護される
     * cacheDir: XNNPackが使用するキャッシュディレクトリ（指定がない場合は context.cacheDir）
     * forceScan: true の場合、recentCacheFiles を再スキャンする（デフォルト: true）
     *            false の場合、スキャンをスキップ（モデル読込完了後の呼び出し用）
     */
    fun cleanupCacheIfNeeded(
        context: Context,
        currentModelBaseName: String = "",
        cacheDir: File? = null,
        forceScan: Boolean = true
    ) {
        try {
            if (currentModelBaseName.isNotEmpty()) {
                lastLoadedModelName = currentModelBaseName
                // 現在のセッションの開始時にキャッシュ一覧を記録
                if (forceScan) {
                    recentCacheFiles = (cacheDir ?: context.cacheDir).listFiles()?.map { it.name }?.toSet() ?: emptySet()
                }
            }
            
            val targetCacheDir = cacheDir ?: context.cacheDir
            val cacheSizeMB = getCacheSize(targetCacheDir) / (1024 * 1024)
            
            if (cacheSizeMB > CLEANUP_THRESHOLD_MB) {
                Log.d(TAG, "Cache size ($cacheSizeMB MB) exceeds threshold. Cleaning up old files (protecting model: $lastLoadedModelName)...")
                cleanOldCacheFiles(targetCacheDir, lastLoadedModelName)
                
                val newSizeMB = getCacheSize(targetCacheDir) / (1024 * 1024)
                Log.d(TAG, "Cache cleaned: $cacheSizeMB MB → $newSizeMB MB")
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error during cache cleanup", e)
        }
    }

    /**
     * Phase 11: XNNPackキャッシュ検証 - 破損検出と自動削除
     * Engine.initialize() 前に呼び出して、壊れたキャッシュを事前削除
     */
    fun validateAndRepairCacheIfNeeded(cacheDirPath: String?): Boolean {
        if (cacheDirPath.isNullOrBlank()) return true
        
        return try {
            val cacheDir = File(cacheDirPath)
            if (!cacheDir.exists() || !cacheDir.isDirectory) {
                Log.d(TAG, "Cache directory does not exist: $cacheDirPath")
                return true
            }
            
            // XNNPackキャッシュファイルをスキャン（*.bin, *.ckpt など）
            val cacheFiles = cacheDir.listFiles { file ->
                file.isFile && (file.name.endsWith(".bin") || 
                               file.name.endsWith(".ckpt") ||
                               file.name.contains("xnnpack", ignoreCase = true))
            } ?: emptyArray()
            
            if (cacheFiles.isEmpty()) {
                Log.d(TAG, "No XNNPack cache files found in $cacheDirPath")
                return true
            }
            
            // 破損しているように見えるファイルを検出（サイズが異常に小さい等）
            val suspiciousFiles = cacheFiles.filter { file ->
                file.length() < 1024  // 1KB未満は疑わしい
            }
            
            if (suspiciousFiles.isNotEmpty()) {
                Log.w(TAG, "Detected ${suspiciousFiles.size} suspicious cache files (likely corrupted). Deleting...")
                suspiciousFiles.forEach { file ->
                    val deleted = file.delete()
                    Log.d(TAG, "Deleted suspicious cache file: ${file.name} (success=$deleted)")
                }
                return true  // 削除成功 - Engine 初期化前に清潔な状態
            }
            
            Log.d(TAG, "Cache validation passed: ${cacheFiles.size} files OK")
            true
        } catch (e: Exception) {
            Log.w(TAG, "Error validating cache (will proceed anyway)", e)
            true  // エラーでも初期化は続行
        }
    }
    
    /**
     * モデル読み込み完了後、新規生成されたキャッシュファイルを記録
     * TFLiteが動的に生成するキャッシュファイルをトラッキング
     */
    fun updateRecentCacheFiles(context: Context) {
        try {
            val currentFiles = context.cacheDir.listFiles()?.map { it.name }?.toSet() ?: emptySet()
            val newFiles = currentFiles - recentCacheFiles
            if (newFiles.isNotEmpty()) {
                Log.d(TAG, "Detected ${newFiles.size} new cache files generated by TFLite")
            }
            recentCacheFiles = currentFiles
        } catch (e: Exception) {
            Log.e(TAG, "Error updating recent cache files", e)
        }
    }
    
    /**
     * 指定モデルのキャッシュファイル個数をカウント
     * 例: modelBaseName = "gemma-3n-e4b" → "gemma-3n-e4b.task_*.bin" の個数を返す
     */
    fun getModelCacheFileCount(context: Context, modelBaseName: String): Int {
        return try {
            val cacheDir = context.cacheDir
            val modelFiles = cacheDir.listFiles()?.filter { file ->
                file.isFile && file.name.contains(modelBaseName, ignoreCase = true) &&
                file.name.endsWith(".bin", ignoreCase = true)
            } ?: emptyList()
            modelFiles.count()
        } catch (e: Exception) {
            Log.e(TAG, "Error counting model cache files", e)
            0
        }
    }
    
    /**
     * モデルのキャッシュファイル個数をチェック（不足は全削除）
     * 返り値: true = キャッシュ OK、false = キャッシュ不足で全削除した
     */
    fun validateAndRecoverCacheFiles(context: Context, modelBaseName: String, expectedCount: Int = 6): Boolean {
        return try {
            val currentCount = getModelCacheFileCount(context, modelBaseName)
            Log.d(TAG, "Cache file count check: $modelBaseName has $currentCount files (expected: $expectedCount)")
            
            if (currentCount < expectedCount) {
                Log.w(TAG, "Cache incomplete! Expected $expectedCount files but found $currentCount. Deleting all cache files for regeneration.")
                deleteAllModelCacheFiles(context, modelBaseName)
                false
            } else {
                true
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error during cache validation", e)
            false
        }
    }
    
    /**
     * 指定モデルの全キャッシュファイルを削除
     * モデルロード前に不完全なキャッシュを消して再生成させる用
     */
    fun deleteAllModelCacheFiles(context: Context, modelBaseName: String) {
        try {
            val cacheDir = context.cacheDir
            val modelFiles = cacheDir.listFiles()?.filter { file ->
                file.isFile && file.name.contains(modelBaseName, ignoreCase = true) &&
                file.name.endsWith(".bin", ignoreCase = true)
            } ?: emptyList()
            
            if (modelFiles.isEmpty()) {
                Log.d(TAG, "No cache files to delete for $modelBaseName")
                return
            }
            
            var deletedCount = 0
            var deletedSizeMB = 0L
            
            for (file in modelFiles) {
                val fileSize = file.length()
                if (file.delete()) {
                    deletedCount++
                    deletedSizeMB += fileSize / (1024 * 1024)
                    Log.d(TAG, "Deleted cache file for regeneration: ${file.name} (${fileSize / (1024 * 1024)} MB)")
                }
            }
            
            Log.i(TAG, "Deleted all cache files for $modelBaseName: $deletedCount files, ${deletedSizeMB}MB freed")
        } catch (e: Exception) {
            Log.e(TAG, "Error deleting model cache files", e)
        }
    }
    
    /**
     * キャッシュディレクトリの総容量を計算
     */
    private fun getCacheSize(dir: File): Long {
        var size = 0L
        if (dir.isDirectory) {
            dir.listFiles()?.forEach { file ->
                size += if (file.isDirectory) {
                    getCacheSize(file)
                } else {
                    file.length()
                }
            }
        }
        return size
    }
    
    /**
     * 古いキャッシュファイルを削除（保守的なLRU戦略）
     * 現在のモデルのキャッシュファイルは保護される
     */
    private fun cleanOldCacheFiles(dir: File, currentModelBaseName: String = "") {
        if (!dir.isDirectory) return
        
        val files = dir.listFiles()?.filter { it.isFile } ?: return
        
        // 保護対象：
        // 1. currentModelBaseName を含むファイル
        // 2. recentCacheFiles に含まれるファイル（このセッション中に出現したファイル）
        val protectedFiles = mutableSetOf<String>()
        
        if (currentModelBaseName.isNotEmpty()) {
            val modelFiles = files.filter { file ->
                file.name.contains(currentModelBaseName, ignoreCase = true)
            }
            protectedFiles.addAll(modelFiles.map { it.name })
        }
        
        // セッション中に出現したファイルを保護
        protectedFiles.addAll(recentCacheFiles)
        
        // 削除対象：保護対象外のファイル
        val unprotectedFiles = files
            .filter { file -> file.name !in protectedFiles }
            .sortedBy { it.lastModified() }
        
        // ターゲットサイズ：250MB に削減（古いセッションキャッシュをクリア）
        val targetSizeBytes = 250L * 1024 * 1024
        val currentSize = unprotectedFiles.sumOf { it.length() }
        
        if (currentSize <= targetSizeBytes) {
            Log.d(TAG, "Cache size within acceptable range, no cleanup needed")
            return
        }
        
        var deletedSize = 0L
        var deletedCount = 0
        
        for (file in unprotectedFiles) {
            val currentRemaining = currentSize - deletedSize
            if (currentRemaining <= targetSizeBytes) break
            
            val fileSize = file.length()
            if (file.delete()) {
                deletedSize += fileSize
                deletedCount++
                Log.d(TAG, "Deleted cache file: ${file.name}")
            }
        }
        
        Log.d(TAG, "Cleanup completed: deleted $deletedCount files, freed ${deletedSize / (1024 * 1024)}MB")
    }
}
